name: Backend CI/CD Pipeline

on:
  push:
    branches: [ "main", "develop" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker Image
        run: |
          # 브랜치별로 다른 태그 생성 (main -> latest, dev -> dev)
          TAG=${{ github.ref_name == 'main' && 'latest' || 'dev' }}
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/akiba-backend:$TAG .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/akiba-backend:$TAG

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    env:
      IS_PROD: ${{ github.ref_name == 'main' }}
      DB_PASSWORD: ${{ github.ref_name == 'main' && secrets.PROD_DB_PASSWORD || secrets.DEV_DB_PASSWORD }}
    steps:
      - name: SSH to EC2 and Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            
            mkdir -p /home/ubuntu/docker/config
            
            echo "DB_PASSWORD=${{ env.DB_PASSWORD }}" > /home/ubuntu/docker/config/.env
            echo "DOCKERHUB_USERNAME=${{ secrets.DOCKERHUB_USERNAME }}" >> /home/ubuntu/docker/config/.env
            echo "${{ github.ref_name == 'main' && secrets.PROD_YML || secrets.DEV_YML }}" > /home/ubuntu/docker/config/application.yml
            
            cd /home/ubuntu/docker
            
            export TAG=${{ github.ref_name == 'main' && 'latest' || 'dev' }}
            docker compose -f ${{ env.IS_PROD && 'docker-compose.app.prod.yml' || 'docker-compose.app.dev.yml' }} pull
            docker compose -f ${{ env.IS_PROD && 'docker-compose.app.prod.yml' || 'docker-compose.app.dev.yml' }} up -d
